public class B777Protocol {

    public static final int HEADING = 0; // heading in degrees
    public static final int APHEADING = 1; // AP heading bug
    public static final int VORLID = 2;
    public static final int VORLDME = 3;
    public static final int VORLDMEINRANGE = 4;
    public static final int VORLINRANGE = 5;
    public static final int VORLFREQ = 6;
    public static final int SWITCHLEFT = 7;
    public static final int VORLDIR = 8;
    public static final int VORRID = 9;
    public static final int VORRDME = 10;
    public static final int VORRDMEINRANGE = 11;
    public static final int VORRINRANGE = 12;
    public static final int VORRFREQ = 13;
    public static final int SWITCHRIGHT = 14;
    public static final int VORRDIR = 15;
    public static final int ADFLID = 16;
    public static final int ADFLINRANGE = 17;
    public static final int ADFLFREQ = 18;
    public static final int ADFLDIR = 19;
    public static final int ADFRID = 20;
    public static final int ADFRINRANGE = 21;
    public static final int ADFRFREQ = 22;
    public static final int ADFRDIR = 23;
    public static final int RADIALDIR = 24;
    public static final int RADIALHEAD = 25;
    public static final int RADIALDEF = 26;
    public static final int GSDEF = 27;
    public static final int MODE = 28;
    public static final int RANGE = 29;
    public static final int MODEBUT = 30;
    public static final int TRUESPEED = 31;
    public static final int GROUNDSPEED = 32;
    public static final int WINDHEADING = 33;
    public static final int WINDSPEED = 34;
    public static final int LATITUDE = 35;
    public static final int LONGITUDE = 36;
    public static final int LATWP1 = 37;
    public static final int LONWP1 = 38;
    public static final int LATWP2 = 39;
    public static final int LONWP2 = 40;
    public static final int LATWP3 = 41;
    public static final int LONWP3 = 42;
    public static final int LATWP4 = 43;
    public static final int LONWP4 = 44;
    public static final int LATWP5 = 45;
    public static final int LONWP5 = 46;
    public static final int LATWP6 = 47;
    public static final int LONWP6 = 48;
    public static final int LATWP7 = 49;
    public static final int LONWP7 = 50;
    public static final int LATWP8 = 51;
    public static final int LONWP8 = 52;
    public static final int LATWP9 = 53;
    public static final int LONWP9 = 54;
    public static final int LATWP10 = 55;
    public static final int LONWP10 = 56;
    public static final int LATWP11 = 57;
    public static final int LONWP11 = 58;
    public static final int LATWP12 = 59;
    public static final int LONWP12 = 60;
    public static final int CURRENTWP = 61;
    public static final int NUMWP = 62;

}
